spring:
  application:
          name: post

  datasource:
    url: jdbc:mysql://localhost:3306/postdb
    username: root
    password: rakesh@#1997
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
      server:
        port: 8081